#### Introduction

The air quality data for this segment has been divided into three different csv files.

`info.csv` has the data hour by hour data about the concentration of polutants in the air and the status of the intruments.
`item_info` has the data for items and levels of concetration.
`station_info` has the data for measuring stations.

Read in all the three datasets and then print the first five rows.

You can download the dataset from kaggle website: https://www.kaggle.com/bappekim/air-pollution-in-seoul

In [36]:
import pandas as pd

In [37]:
data = pd.read_csv("/content/sample_data/Measurement_info.csv")
data.head()

   Measurement date  Station code  Item code  Average value  Instrument status
0  2017-01-01 00:00         101.0        1.0          0.004                0.0
1  2017-01-01 00:00         101.0        3.0          0.059                0.0
2  2017-01-01 00:00         101.0        5.0          1.200                0.0
3  2017-01-01 00:00         101.0        6.0          0.002                0.0
4  2017-01-01 00:00         101.0        8.0         73.000                0.0

In [38]:
item = pd.read_csv("/content/sample_data/Measurement_item_info.csv")
item.head()

,Item code,Item name,Unit of measurement,Good(Blue),Normal(Green),Bad(Yellow),Very bad(Red)
0,1,SO2,ppm,0.02,0.05,0.15,1.0
1,3,NO2,ppm,0.03,0.06,0.20,2.0
2,5,CO,ppm,2.00,9.00,15.00,50.0
3,6,O3,ppm,0.03,0.09,0.15,0.5
4,8,PM10,Mircrogram/m3,30.00,80.00,150.00,600.0

In [39]:
station = pd.read_csv("/content/sample_data/Measurement_station_info.csv")
station.head()

,Station code,Station name(district),Address,Latitude,Longitude
0,101,Jongno-gu,"19, Jong-ro 35ga-gil, Jongno-gu, Seoul, Republ...",37.572016,127.005008
1,102,Jung-gu,"15, Deoksugung-gil, Jung-gu, Seoul, Republic o...",37.564263,126.974676
2,103,Yongsan-gu,"136, Hannam-daero, Yongsan-gu, Seoul, Republic...",37.540033,127.004850
3,104,Eunpyeong-gu,"215, Jinheung-ro, Eunpyeong-gu, Seoul, Republi...",37.609823,126.934848
4,105,Seodaemun-gu,"32, Segeomjeong-ro 4-gil, Seodaemun-gu, Seoul,...",37.593742,126.949679

#### Question 1

Create a new Dataframe whcih has information about the item code and item name

In [40]:
sub_item = item[['Item code', 'Item name']]
display(sub_item.head())

   Item code Item name
0          1       SO2
1          3       NO2
2          5        CO
3          6        O3
4          8      PM10

#### Question 2

Create a new Dataframe whcih has information about the station code and station name

In [41]:
sub_station = station[['Station code', 'Station name(district)']]
display(sub_station.head())

   Station code Station name(district)
0           101              Jongno-gu
1           102                Jung-gu
2           103             Yongsan-gu
3           104           Eunpyeong-gu
4           105           Seodaemun-gu

### Question 3

In the `data` DataFrame add in a column displaying the names of the items.

In [42]:
data_i = data.copy()
data_i = pd.merge(data_i, sub_item, on='Item code', how='left')
display(data_i.head())

,Measurement date,Station code,Item code,Average value,Instrument status,Item name
0,2017-01-01 00:00,101.0,1.0,0.004,0.0,SO2
1,2017-01-01 00:00,101.0,3.0,0.059,0.0,NO2
2,2017-01-01 00:00,101.0,5.0,1.200,0.0,CO
3,2017-01-01 00:00,101.0,6.0,0.002,0.0,O3
4,2017-01-01 00:00,101.0,8.0,73.000,0.0,PM10

### Question 4

In the `data_i` DataFrame add in a column displaying the names of the stations.

In [43]:
data_s = pd.merge(data_i, sub_station, on='Station code', how='left')
display(data_s.head())

,Measurement date,Station code,Item code,Average value,Instrument status,Item name,Station name(district)
0,2017-01-01 00:00,101.0,1.0,0.004,0.0,SO2,Jongno-gu
1,2017-01-01 00:00,101.0,3.0,0.059,0.0,NO2,Jongno-gu
2,2017-01-01 00:00,101.0,5.0,1.200,0.0,CO,Jongno-gu
3,2017-01-01 00:00,101.0,6.0,0.002,0.0,O3,Jongno-gu
4,2017-01-01 00:00,101.0,8.0,73.000,0.0,PM10,Jongno-gu

### Question 5

In the `data_s` DataFrame drop the columns `Station code` and `Item code`. As these columns have not become redundant. You can find the relevant function in the pandas library [here](https://pandas.pydata.org/docs/reference/index.html).

In [44]:
data_s = data_s.drop(columns=['Station code', 'Item code'])
display(data_s.head())

,Measurement date,Average value,Instrument status,Item name,Station name(district)
0,2017-01-01 00:00,0.004,0.0,SO2,Jongno-gu
1,2017-01-01 00:00,0.059,0.0,NO2,Jongno-gu
2,2017-01-01 00:00,1.200,0.0,CO,Jongno-gu
3,2017-01-01 00:00,0.002,0.0,O3,Jongno-gu
4,2017-01-01 00:00,73.000,0.0,PM10,Jongno-gu

### Question 6

Given below are the meanings of the values in the `Instrument status`.

- 0: Normal
- 1: Need for calibration
- 2: Abnormal
- 4: Power cut off
- 8: Under repair
- 9: Abnormal data

Using the information given above, add a column in the `data` DataFrame to give the status of the intsruments. Then drop the `Instrument status` column.  

Hint: First create a dictionary from the data, then use the same dictionary to create a DataFrame and then merge the DataFrame. with `data`

In [45]:
status_dict = {
    0: 'Normal',
    1: 'Need for calibration',
    2: 'Abnormal',
    4: 'Power cut off',
    8: 'Under repair',
    9: 'Abnormal data'
}
status_map_df = pd.DataFrame(list(status_dict.items()), columns=['Instrument status', 'Instrument status description'])
display(status_map_df.head())

   Instrument status Instrument status description
0                  0                        Normal
1                  1          Need for calibration
2                  2                      Abnormal
3                  4                 Power cut off
4                  8                  Under repair

In [46]:
data = pd.merge(data, status_map_df, on='Instrument status', how='left')
display(data.head())

,Measurement date,Station code,Item code,Average value,Instrument status,Instrument status description
0,2017-01-01 00:00,101.0,1.0,0.004,0.0,Normal
1,2017-01-01 00:00,101.0,3.0,0.059,0.0,Normal
2,2017-01-01 00:00,101.0,5.0,1.200,0.0,Normal
3,2017-01-01 00:00,101.0,6.0,0.002,0.0,Normal
4,2017-01-01 00:00,101.0,8.0,73.000,0.0,Normal

In [48]:
data = data.drop(columns=['Instrument status'])
display(data.head())

,Measurement date,Station code,Item code,Average value,Instrument status description
0,2017-01-01 00:00,101.0,1.0,0.004,Normal
1,2017-01-01 00:00,101.0,3.0,0.059,Normal
2,2017-01-01 00:00,101.0,5.0,1.200,Normal
3,2017-01-01 00:00,101.0,6.0,0.002,Normal
4,2017-01-01 00:00,101.0,8.0,73.000,Normal

In [ ]:
data =

### Question 7

Extract the time series data, that is year, month, date and hour form the `Measurement date` column. Once all the data is extrcted drop the `Measurement date` column.

This operation might take some time as the dataset we are working with is very large.

In [50]:
data['Measurement date'] = pd.to_datetime(data['Measurement date'], format='mixed', errors='coerce')
data['Year'] = data['Measurement date'].dt.year
data['Month'] = data['Measurement date'].dt.month
data['Date'] = data['Measurement date'].dt.day
data['Hour'] = data['Measurement date'].dt.hour
data = data.drop(columns=['Measurement date'])
data.head()

,Station code,Item code,Average value,Instrument status description,Year,Month,Date,Hour
0,101.0,1.0,0.004,Normal,2017.0,1.0,1.0,0.0
1,101.0,3.0,0.059,Normal,2017.0,1.0,1.0,0.0
2,101.0,5.0,1.200,Normal,2017.0,1.0,1.0,0.0
3,101.0,6.0,0.002,Normal,2017.0,1.0,1.0,0.0
4,101.0,8.0,73.000,Normal,2017.0,1.0,1.0,0.0

In [51]:
processed_data = processed_data.drop(columns=['Measurement date'])
display(processed_data.head())

KeyError: "['Measurement date'] not found in axis"

In [52]:
processed_data = pd.merge(data_s, status_map_df, on='Instrument status', how='left')
processed_data = processed_data.drop(columns=['Instrument status'])
display(processed_data.head())

,Measurement date,Average value,Item name,Station name(district),Instrument status description
0,2017-01-01 00:00,0.004,SO2,Jongno-gu,Normal
1,2017-01-01 00:00,0.059,NO2,Jongno-gu,Normal
2,2017-01-01 00:00,1.200,CO,Jongno-gu,Normal
3,2017-01-01 00:00,0.002,O3,Jongno-gu,Normal
4,2017-01-01 00:00,73.000,PM10,Jongno-gu,Normal